name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10.18"

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: "17"

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
        build-essential \
        git \
        zip \
        unzip \
        openjdk-17-jdk \
        autoconf \
        libtool \
        pkg-config \
        zlib1g-dev \
        libncurses5 \
        libstdc++6 \
        libffi-dev \
        libssl-dev \
        libsqlite3-dev \
        libltdl-dev \
        libc6-dev \
        wget \
        curl \
        cmake \
        ninja-build

    - name: Install Buildozer
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython

    - name: Install Android SDK
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        cd $HOME/android-sdk

        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O sdk.zip
        unzip sdk.zip
        rm sdk.zip

        mkdir -p cmdline-tools/latest
        mv cmdline-tools/* cmdline-tools/latest/ || true

        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH

    - name: Install SDK packages
      run: |
        yes | sdkmanager --licenses

        sdkmanager \
        "platform-tools" \
        "platforms;android-33" \
        "build-tools;33.0.2" \
        "ndk;25.2.9519653"

    - name: Build APK
      run: |
        buildozer android clean
        buildozer android debug

    - name: Upload build logs
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: .buildozer

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: bin/*.apk
